server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?characterEncoding=utf-8
    username: root
    password: 1011

  session:
    store-type: redis


  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: classpath:/templates/


  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
    static-path-pattern: /static/**
  redis:
    port: 6379
    host: 192.168.25.129



# freemarker

# mybatis
mybatis:
  mapper-locations: classpath:com/starichat/onlineexam/dao/*.xml
  config-location: classpath:mybatis-config.xml

